
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'F6F5DBC9CA554D6E45C3E575899B6838'
    
_lr_action_items = {'TABLE':([3,],[5,]),'$end':([1,2,4,36,50,],[-1,0,-2,-3,-4,]),'NUMBER':([35,],[43,]),'IF':([5,],[8,]),'PRIMARY':([12,24,25,26,28,30,48,],[15,-23,32,-21,15,15,-22,]),'COMMA':([7,13,20,24,25,26,34,41,42,48,52,54,],[-5,-6,28,-23,-12,-21,-13,-14,-17,-22,55,-16,]),'NOT':([8,],[11,]),'IDENTIFIER':([5,10,12,14,17,28,30,31,33,38,47,55,],[7,13,17,7,24,17,17,40,7,44,52,52,]),'DOT':([6,7,],[10,-7,]),'CREATE':([0,1,36,50,],[3,3,-3,-4,]),'RPAREN':([7,13,16,18,19,20,24,25,26,34,37,39,40,41,42,43,44,46,48,51,52,53,54,56,],[-5,-6,-10,27,-9,-8,-23,-12,-21,-13,-11,45,46,-14,-17,48,49,-15,-22,54,-19,-18,-16,-20,]),'LPAREN':([7,9,13,22,23,24,26,29,42,],[-5,12,-6,30,31,-23,35,38,47,]),'EXISTS':([11,],[14,]),'KEY':([15,21,32,],[23,29,41,]),'SEMICOLON':([27,45,],[36,50,]),'REFERENCES':([24,25,26,48,49,],[-23,33,-21,-22,33,]),'FOREIGN':([12,28,30,],[21,21,21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'column_name_list':([47,55,],[51,56,]),'foreign_key_definition':([12,28,30,],[16,16,16,]),'column_definitions':([12,28,30,],[18,37,39,]),'table_definition':([0,1,],[1,1,]),'primary_key_definition':([12,28,30,],[19,19,19,]),'reference_definition':([25,49,],[34,53,]),'table_name':([5,14,33,],[9,22,42,]),'table_definitions':([0,1,],[2,4,]),'data_type':([17,],[25,]),'column_definition':([12,28,30,],[20,20,20,]),'type':([17,],[26,]),'schema':([5,14,33,],[6,6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> table_definitions","S'",1,None,None,None),
  ('table_definitions -> table_definition','table_definitions',1,'p_table_definitions','ddlparser.py',120),
  ('table_definitions -> table_definition table_definitions','table_definitions',2,'p_table_definitions','ddlparser.py',121),
  ('table_definition -> CREATE TABLE table_name LPAREN column_definitions RPAREN SEMICOLON','table_definition',7,'p_table_definition','ddlparser.py',129),
  ('table_definition -> CREATE TABLE IF NOT EXISTS table_name LPAREN column_definitions RPAREN SEMICOLON','table_definition',10,'p_table_definition','ddlparser.py',130),
  ('table_name -> IDENTIFIER','table_name',1,'p_table_name','ddlparser.py',142),
  ('table_name -> schema DOT IDENTIFIER','table_name',3,'p_table_name','ddlparser.py',143),
  ('schema -> IDENTIFIER','schema',1,'p_schema','ddlparser.py',154),
  ('column_definitions -> column_definition','column_definitions',1,'p_column_definitions','ddlparser.py',158),
  ('column_definitions -> primary_key_definition','column_definitions',1,'p_column_definitions','ddlparser.py',159),
  ('column_definitions -> foreign_key_definition','column_definitions',1,'p_column_definitions','ddlparser.py',160),
  ('column_definitions -> column_definition COMMA column_definitions','column_definitions',3,'p_column_definitions','ddlparser.py',161),
  ('column_definition -> IDENTIFIER data_type','column_definition',2,'p_column_definition','ddlparser.py',174),
  ('column_definition -> IDENTIFIER data_type reference_definition','column_definition',3,'p_column_definition','ddlparser.py',175),
  ('column_definition -> IDENTIFIER data_type PRIMARY KEY','column_definition',4,'p_column_definition','ddlparser.py',176),
  ('primary_key_definition -> PRIMARY KEY LPAREN IDENTIFIER RPAREN','primary_key_definition',5,'p_primary_key_definition','ddlparser.py',187),
  ('reference_definition -> REFERENCES table_name LPAREN column_name_list RPAREN','reference_definition',5,'p_reference_definition','ddlparser.py',191),
  ('reference_definition -> REFERENCES table_name','reference_definition',2,'p_reference_definition','ddlparser.py',192),
  ('foreign_key_definition -> FOREIGN KEY LPAREN IDENTIFIER RPAREN reference_definition','foreign_key_definition',6,'p_foreign_key_definition','ddlparser.py',198),
  ('column_name_list -> IDENTIFIER','column_name_list',1,'p_column_name_list','ddlparser.py',203),
  ('column_name_list -> IDENTIFIER COMMA column_name_list','column_name_list',3,'p_column_name_list','ddlparser.py',204),
  ('data_type -> type','data_type',1,'p_data_type','ddlparser.py',212),
  ('data_type -> type LPAREN NUMBER RPAREN','data_type',4,'p_data_type','ddlparser.py',213),
  ('type -> IDENTIFIER','type',1,'p_type','ddlparser.py',221),
]
